semanticloud/core/urls.py
__author__ = 'maurizio'

from django.conf.urls import url
import views


urlpatterns = [
    url(r'^get_lemmas/', views.get_lemmas_from_synset, name='get_lemmas'),
    url(r'^get_synonyms/$', views.get_synonyms, name='get_synonyms'),
    url(r'^get_part/$', views.get_meronyms, name='get_meronyms'),
    url(r'^get_more_general/$', views.get_more_general, name='get_more_general'),
    url(r'^get_more_specific/$', views.get_more_specific, name='get_more_specific'),
    url(r'get_lemmas_batch/', views.get_lemmas_from_synsets_batch),
    url(r'get_synsets/', views.get_synsets_from_word),
    url(r'get_synsets_batch/', views.get_synsets_from_words_batch),
    url(r'get_hypernyms/', views.get_hypernym),
    url(r'get_hypernyms_batch/', views.get_hypernym_batch),
    url(r'get_r_hypernyms/', views.get_r_hypernym),
    url(r'get_r_hypernyms_batch/', views.get_r_hypernym_batch),
    url(r'get_r_hyponyms/', views.get_r_hyponym),
    url(r'get_r_hyponyms_batch/', views.get_r_hyponym_batch),
    url(r'get_hyponyms/', views.get_hyponyms_view),
    url(r'get_hyponyms_batch/', views.get_hyponyms_view_batch),
    url(r'get_antonyms/', views.get_antonyms_view),
    url(r'get_antonyms_batch/', views.get_antonyms_view_batch),
    url(r'get_homonyms/', views.get_homonyms_view),
    url(r'get_homonyms_batch/', views.get_homonyms_view_batch),
    url(r'get_derivational/', views.get_derivational_view),
    url(r'get_derivational_batch/', views.get_derivational_view_batch),
    url(r'get_lex_domain/', views.get_lex_domains),
    url(r'get_lex_domain_batch/', views.get_lex_domains_batch),
    ]

semanticloud/semanticloud/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView
from views import logout_user, login_user, welcome, ApplicationRegistration, ApplicationUpdate, TryApi, RaiseForbidden, Pay, StartPayment, UpdateSemantic, \
    TryApiHome, ApplicationList
from django.contrib.auth.views import password_change_done, password_change
from django.views.generic import RedirectView


urlpatterns = [
    url('^$', welcome),
    url(r'^profile', login_required(TemplateView.as_view(template_name='profile.html')), name='profile'),
    url(r'^raise403', RaiseForbidden.as_view(), name='RaiseForbidden'),
    url(r'^home', TemplateView.as_view(template_name='home.html')),
    # url(r'^home', TemplateView.as_view(template_name='base.html')),
    url(r'^doc', TemplateView.as_view(template_name='doc_template/index.html')),
    url(r'^login/$', login_user, name='login'),
    url(r'^logout/$', logout_user),
    url(r'^admin/', admin.site.urls),
    url(r'^pay/', Pay.as_view(), name='pay'),
    url(r'^contacts/', TemplateView.as_view(template_name='contacts.html'), name='contacts'),
    url(r'^howto/$', TemplateView.as_view(template_name='howto.html'), name='howto'),
    url(r'^start_payment/', StartPayment.as_view(), name='StartPayment'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^o/applications/$', ApplicationList.as_view()),
    url(r'^o/applications/register/$', permission_required('is_staff')(ApplicationRegistration.as_view())),
    url(r'^o/applications/(?P<pk>\d+)/update/$', ApplicationUpdate.as_view(), name="update"),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^api/', include('core.urls')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    # url(r'^password_change/$', password_change, {'template_name': 'password_change_form.html'}, name='password_change'),
    url(r'^password_change/done/$', RedirectView.as_view(pattern_name='profile'), name='password_change_done'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^try_api/$', TryApi.as_view()),
    url(r'^try_api_home/$', TryApiHome.as_view()),
    url(r'^update_sematic/$', UpdateSemantic.as_view()),
]

semanticloud/semanticloud/models.py
from django.core.urlresolvers import reverse

__author__ = 'maurizio'

from django.db import models
from oauth2_provider.models import AbstractApplication
from django.utils.translation import ugettext_lazy as _

GRANT_CLIENT_CREDENTIALS = 'client-credentials'
GRANT_TYPES = (
    (GRANT_CLIENT_CREDENTIALS, _('Client credentials')),)


class Tier(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=3000)
    monthly_request_limit = models.IntegerField()

    def __unicode__(self):
        return str(self.name)


class CustomApplication(AbstractApplication):
    activation_data = models.DateField(auto_now_add=True, null=True)
    tier = models.ForeignKey(Tier, null=True, editable=True)
    tier_paid = models.ForeignKey(Tier, null=True, editable=False, related_name='tier_paid', blank=True)
    auto_renewal = models.BooleanField(default=False, editable=False)
    monthly_requests = models.IntegerField(default=0, editable=False)


CustomApplication._meta.get_field('authorization_grant_type').choices = GRANT_TYPES
CustomApplication._meta.get_field('authorization_grant_type').default = GRANT_CLIENT_CREDENTIALS
# CustomApplication._meta.get_field('user').editable = False
CustomApplication._meta.get_field('client_id').editable = False
CustomApplication._meta.get_field('client_secret').editable = False
# CustomApplicationProxy._meta.get_field('tier').editable = True

semanticloud/semanticloud/forms.py
from django.core.validators import RegexValidator

__author__ = 'maurizio'

from django import forms
from datetime import date

numeric = RegexValidator(r'^[0-9]*$', 'Only alphanumeric characters are allowed.')


class PaymentForm(forms.Form):
    FirstName = forms.CharField(label='First name', max_length=100)
    LastName = forms.CharField(label='Last name', max_length=100)
    Month = forms.IntegerField(label='Month', max_value=12, min_value=1)
    # Year = forms.IntegerField(label='Year', max_value=date.today().year + 15, min_value=2011)
    Year = forms.IntegerField(label='Year', max_value=date.today().year + 15, min_value=date.today().year)
    Number = forms.CharField(label='Number', validators=[numeric])
    Verification = forms.CharField(label='Verification', validators=[numeric])

semanticloud/semanticloud/views.py
from django.contrib.auth.decorators import user_passes_test
from requests import ConnectionError

__author__ = 'maurizio'

from django.db.models import Q
from billing.utils.credit_card import CardNotSupported
from core.utils import get_lemmas
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect, ensure_csrf_cookie, requires_csrf_token
from setuptools.package_index import unique_everseen
import json
from billing import get_gateway
from billing import CreditCard
from requests_oauthlib import OAuth2Session
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelform_factory
from django.views.generic import CreateView, UpdateView, View, ListView
from oauth2_provider.models import get_application_model
from models import Tier
from oauth2_provider.views.application import ApplicationOwnerIsUserMixin
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render_to_response, redirect, render, get_object_or_404
from django.template import RequestContext
from django.utils.datastructures import MultiValueDictKeyError
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseRedirect, HttpResponseNotAllowed
from django.conf import settings
from forms import PaymentForm
from oauthlib.oauth2 import BackendApplicationClient, TokenExpiredError
from django.db import transaction
from core import utils
from core.models import Sense
from models import CustomApplication


def login_user(request):
    next_url = request.POST.get('next') or '/'
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            # applications = CustomApplication.objects.filter(user=user)
            # request.session['applications'] = serializers.serialize("json", applications)
            if next_url is not None:
                return redirect(next_url)
            else:
                return redirect('/')
        else:
            return redirect('login')
    else:
        try:
            context_par = {'next': request.GET['next']}
        except MultiValueDictKeyError:
            context_par = {'next': '/o/applications'}
        return render_to_response('login.html', context=context_par, context_instance=RequestContext(request))


def logout_user(request):
    logout(request)
    return redirect('/home')


def welcome(request):
    if request.user.is_authenticated():
        return redirect('/o/applications')
    else:
        return redirect('/home')


class ApplicationRegistration(LoginRequiredMixin, CreateView):
    """
    View used to register a new Application for the request.user
    """
    template_name = "oauth2_provider/application_registration_form.html"

    def get_form_class(self):
        """
        Returns the form class for the application model
        """
        if self.request.user.is_superuser or self.request.user.is_staff:
            return modelform_factory(
                get_application_model(),
                fields=(
                    # 'user', 'name', 'client_type', 'tier', 'authorization_grant_type', 'redirect_uris', 'auto_renewal')
                    'user', 'name', 'client_type', 'tier', 'authorization_grant_type', 'redirect_uris')
            )
        else:
            return modelform_factory(
                get_application_model(),
                # fields=('name', 'client_type', 'tier', 'authorization_grant_type', 'redirect_uris', 'auto_renewal')
                fields=('name', 'client_type', 'authorization_grant_type', 'redirect_uris')
            )

    @transaction.atomic
    def form_valid(self, form):
        if form.instance.tier is None:
            form.instance.tier = Tier.objects.get(name='Free')
        if form.instance.tier == Tier.objects.get(name='Free') and len(
                get_application_model().objects.filter(user=self.request.user).filter(
                    tier=Tier.objects.get(name='Free'))) > 0:
            # form.errors['tier'] = "You can't have more than one free tier"
            form.errors['name'] = "You can't have more than one free tier"
            print form.errors
            return super(ApplicationRegistration, self).form_invalid(form)
        else:
            if len(get_application_model().objects.filter(user=self.request.user).exclude(
                    tier=Tier.objects.get(name='Free')).filter(
                tier_paid=None)) > 0 and not self.request.user.is_staff and not settings.BETA:
                form.errors[
                    'tier'] = "You have to pay all your previous applications before you can register another one"
                return super(ApplicationRegistration, self).form_invalid(form)
            else:
                with transaction.atomic():
                    if not self.request.user.is_staff and not self.request.user.is_superuser:
                        form.instance.user = self.request.user
                    application = form.save()
                    if application.tier.name == 'Free':
                        return HttpResponseRedirect('/o/applications/')
                    else:
                        self.request.session['app_to_pay'] = application.id
                        self.request.session['tier'] = application.tier.id
                        if settings.BETA:
                            return HttpResponseRedirect('/o/applications/')
                        else:
                            return HttpResponseRedirect('/pay/')


class ApplicationUpdate(LoginRequiredMixin, ApplicationOwnerIsUserMixin, UpdateView):
    """
    View used to update an application owned by the request.user
    """
    context_object_name = 'application'
    template_name = "oauth2_provider/application_form.html"

    def get_form_class(self):
        """
        Returns the form class for the application model
        """
        if self.request.user.is_superuser or self.request.user.is_staff:
            return modelform_factory(
                get_application_model(),
                fields=(
                    # 'user', 'name', 'client_type', 'tier', 'authorization_grant_type', 'redirect_uris', 'auto_renewal')
                    'user', 'name', 'client_type', 'tier', 'authorization_grant_type', 'redirect_uris')
            )
        else:
            return modelform_factory(
                get_application_model(),
                # fields=('name', 'client_type', 'tier', 'authorization_grant_type', 'redirect_uris', 'auto_renewal')
                fields=('name', 'client_type', 'authorization_grant_type', 'redirect_uris')
            )

    @transaction.atomic
    def form_valid(self, form):
        if form.instance.tier is None:
            print "case1"
            form.instance.tier = Tier.objects.get(name='Free')
        if form.instance.tier == Tier.objects.get(name='Free') and len(
                get_application_model().objects.filter(user=self.request.user).filter(
                    tier=Tier.objects.get(name='Free'))) > 1:
            # form.errors['tier'] = "You can't have more than one free tier"
            # print "case2"
            form.errors['name'] = "You can't have more than one free tier"

            return super(ApplicationUpdate, self).form_invalid(form)
        else:
            if len(get_application_model().objects.filter(user=self.request.user).exclude(
                    tier=Tier.objects.get(name='Free')).filter(
                tier_paid=None)) > 1 and not self.request.user.is_staff and not settings.BETA:
                form.errors[
                    'tier'] = "You have to pay all your previous applications before you can register another one"
                # print "case3"
                return super(ApplicationUpdate, self).form_invalid(form)
            else:
                with transaction.atomic():
                    if not self.request.user.is_staff and not self.request.user.is_superuser:
                        # print "case4"
                        form.instance.user = self.request.user
                    application = form.save()
                    if application.tier.name == 'Free':
                        print "case5"
                        return HttpResponseRedirect('/o/applications/')
                    self.request.session['app_to_pay'] = application.id
                    self.request.session['tier'] = application.tier.id
                    if settings.BETA:
                        return HttpResponseRedirect('/o/applications/')
                    else:
                        return HttpResponseRedirect('/pay/')


class ApplicationList(ApplicationOwnerIsUserMixin, ListView):
    """
    List view for all the applications owned by the request.user
    """

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ApplicationList, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['BETA'] = settings.BETA
        return context

    context_object_name = 'applications'
    template_name = "oauth2_provider/application_list.html"


class RaiseForbidden(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        return HttpResponseForbidden()


class StartPayment(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        request.session['app_to_pay'] = request.GET['application_id']
        request.session['tier'] = request.GET['tier_id']
        return HttpResponseRedirect('/pay/')


class Pay(LoginRequiredMixin, View):
    template_name = "form_payment.html"
    form_class = PaymentForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

semanticloud/semanticloud/templates/oauth2_provider/application_confirm_delete.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% load url from compat %}
{% block content %}
    <div class="block-center">
        <h3 class="block-center-heading">{% trans "Are you sure to delete the application" %} {{ application.name }}?</h3>
        <form method="post" action="{% url 'oauth2_provider:delete' application.pk %}">
            {% csrf_token %}

            <div class="control-group">
                <div class="controls">
                    <a class="btn btn-large" href="{% url "oauth2_provider:list" %}">{% trans "Cancel" %}</a>
                    <input type="submit" class="btn btn-large btn-danger" name="allow" value="{% trans "Delete" %}"/>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

semanticloud/semanticloud/templates/oauth2_provider/application_detail.html
{% extends "base.html" %}

{% load i18n %}
{% load url from compat %}
{% load staticfiles %}

{% block header %}
    {{ block.super }}
    <script src="{% static 'semanticloud/js/directives/navbarHeader.js' %}" type="text/javascript"></script>
    <base href="{% static 'semanticloud/js/directives/' %}"/>
{% endblock header %}
{% block body %}
<body>
    {% verbatim %}
    <navbar-header show-logo="true"></navbar-header>
    {% endverbatim %}
    <br>

    <div class="block-center-aligned">
        <h3 class="block-center-heading">{{ application.name }}</h3>

        <ul class="unstyled">
            <div>
                <b>{% trans "Client id" %}</b>
                <div class="controls-disabled">
                    <input class="input-block-level disabled" disabled type="text" value="{{ application.client_id }}" readonly>
                </div>
                <br>
            </div>

            <div>
                <b>{% trans "Client secret" %}</b>
                <div class="controls-disabled">
                    <input class="input-block-level disabled" type="text" disabled value="{{ application.client_secret }}" readonly>
                </div>
                <br>
            </div>

            <div>
                <b>{% trans "Client type" %}</b>
                <p>{{ application.client_type }}</p>
                <br>
            </div>

            <div>
                <b>{% trans "Authorization Grant Type" %}</b>
                <p>{{ application.authorization_grant_type }}</p>
                <br>
            </div>

            <div>
                <b>{% trans "Redirect Uris" %}</b>
                <div class="controls-disabled">
                    <textarea class="input-block-level disabled" disabled readonly>{{ application.redirect_uris }}</textarea>
                </div>
                <br>
            </div>

            <div>
                <b>{% trans "Tier" %}</b>
                <p>{{ application.tier }}</p>
                <br>
            </div>
            {% if application.tier.name != 'Free' %}
                <div>
                    <b>{% trans "Tier paid" %}</b>
                    <p>{{ application.tier_paid }}</p>
                    <br>
                </div>
            {% endif %}
        </ul>

        <div class="btn-toolbar">
            <a class="btn" href="{% url "oauth2_provider:list" %}">{% trans "Go Back" %}</a>
            <!--{% if application.tier.name != 'Free' and application.tier_paid.name == None %}-->
                <!--<a href="/start_payment/?application_id={{app.id}}&tier_id={{app.tier.id}}" class="btn btn-primary" role="button">Go to payment <span class="glyphicon glyphicon-usd" aria-hidden="true"></span></a>-->
            <!--{% else %}-->
                <!--<a class="btn btn-primary" href="{% url "oauth2_provider:update" application.id %}">{% trans "Edit" %}</a>-->
                <!--{% if application.tier.name != 'Free' %}-->
                    <!--<a href="/start_payment/?application_id={{app.id}}&tier_id={{app.tier.id}}" class="btn btn-primary" role="button">Go to payment <span class="glyphicon glyphicon-usd" aria-hidden="true"></span></a>-->
                <!--{% endif %}-->
            <!--{% endif %}-->

            <a class="btn btn-primary" href="{% url "oauth2_provider:update" application.id %}">{% trans "Edit" %}</a>
            <a class="btn btn-danger" href="{% url "oauth2_provider:delete" application.id %}">{% trans "Delete" %}</a>
        </div>
    </div>
</body>
{% endblock body %}

semanticloud/semanticloud/templates/oauth2_provider/application_form.html
{% extends "base.html" %}

{% load i18n %}
{% load url from compat %}
{% load staticfiles %}

{% block header %}
    {{ block.super }}
    <script src="{% static 'semanticloud/js/directives/navbarHeader.js' %}" type="text/javascript"></script>
    <base href="{% static 'semanticloud/js/directives/' %}"/>
{% endblock header %}
{% block body %}
<body>
    {% verbatim %}
    <navbar-header show-logo="true"></navbar-header>
    {% endverbatim %}
    <br>
    <div class="block-center-aligned">
        <form class="form-horizontal .horizontal-centered" method="post" action="{% block app-form-action-url %}{% url 'oauth2_provider:update' application.id %}{% endblock app-form-action-url %}">
            <!--<div class="help-inline errorlist">{{ form.errors }}</div>-->
            <h3 class="block-center-heading">
                {% block app-form-title %}
                    {% trans "Edit application" %} {{ application.name }}
                {% endblock app-form-title %}
            </h3>
            {% csrf_token %}

            {% for field in form %}
                <div class="control-group {% if field.errors %}error{% endif %}">
                    <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                     {% if field.errors %}
                        <div class="help-inline errorlist">{{ field.errors }}</div>
                     {% endif %}
                    <div class="controls">
                        {{ field }}
                    </div>
                </div>
            {% endfor %}

            <div class="control-group {% if form.non_field_errors %}error{% endif %}">
                {% for error in form.non_field_errors %}
                    <span class="help-inline">{{ error }}</span>
                {% endfor %}
            </div>

            <div class="control-group">
                <div class="controls">
                    <a class="btn" href="{% block app-form-back-url %}{% url "oauth2_provider:detail" application.id %}{% endblock app-form-back-url %}">
                        {% trans "Go Back" %}
                    </a>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>
</body>
{% endblock %}

semanticloud/semanticloud/templates/oauth2_provider/application_registration_form.html
{% extends "oauth2_provider/application_form.html" %}

{% load i18n %}
{% load url from compat %}

{% block app-form-title %}{% trans "Register a new application" %}{% endblock app-form-title %}

{% block app-form-action-url %}{% url 'oauth2_provider:register' %}{% endblock app-form-action-url %}

{% block app-form-back-url %}{% url "oauth2_provider:list" %}"{% endblock app-form-back-url %}

semanticloud/semanticloud/templates/oauth2_provider/authorize.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <div class="block-center">
        {% if not error %}
            <form id="authorizationForm" method="post">
                <h3 class="block-center-heading">{% trans "Authorize" %} {{ application.name }}?</h3>
                {% csrf_token %}

                {% for field in form %}
                    {% if field.is_hidden %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                <p>{% trans "Application requires following permissions" %}</p>
                <ul>
                    {% for scope in scopes_descriptions %}
                        <li>{{ scope }}</li>
                    {% endfor %}
                </ul>

                {{ form.errors }}
                {{ form.non_field_errors }}

                <div class="control-group">
                    <div class="controls">
                        <input type="submit" class="btn btn-large" value="Cancel"/>
                        <input type="submit" class="btn btn-large btn-primary" name="allow" value="Authorize"/>
                    </div>
                </div>
            </form>

        {% else %}
            <h2>Error: {{ error.error }}</h2>
            <p>{{ error.description }}</p>
        {% endif %}
    </div>
{% endblock %}

semanticloud/semanticloud/templates/oauth2_provider/authorized-token-delete.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>{% trans "Are you sure you want to delete this token?" %}</p>
        <input type="submit" value="{% trans "Delete" %}" />
    </form>
{% endblock %}

semanticloud/semanticloud/templates/oauth2_provider/authorized-tokens.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% load url from compat %}
{% block content %}
    <div class="block-center">
    <h1>{% trans "Tokens" %}</h1>
        <ul>
        {% for authorized_token in authorized_tokens %}
            <li>
                {{ authorized_token.application }}
                (<a href="{% url 'oauth2_provider:authorized-token-delete' authorized_token.pk %}">revoke</a>)
            </li>
            <ul>
            {% for scope_name, scope_description in authorized_token.scopes.items %}
                <li>{{ scope_name }}: {{ scope_description }}</li>
            {% endfor %}
            </ul>
        {% empty %}
            <li>{% trans "There are no authorized tokens yet." %}</li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

semanticloud/semanticloud/templates/oauth2_provider/base_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block css %}
        <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    {% endblock css %}

    <style>
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }
        .block-center {
            max-width: 500px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
        }
        .block-center .block-center-heading {
            margin-bottom: 10px;
        }

    </style>
</head>

<body>

<div class="container">
    {% block content %}
    {% endblock content %}
</div>

</body>
</html>